"""Generate a job recipe whose trials are persona x case pairs.

    uv run python application/scripts/generate_vita_case_job.py \
        --job-name appSim-0709-vita-golden-error-recovery-smoke-baseline \
        --model-name openrouter/anthropic/claude-haiku-4.5 \
        --personas persona/datasets/matraix-persona-dev-sample/persona_0042.yaml \
        --smoke-per-error-type 2

Pass ``--all-cases`` instead of ``--smoke-per-error-type`` for the full sweep.
"""

from __future__ import annotations

import argparse
import collections
import itertools
import json
import os
from pathlib import Path
from typing import Any, Mapping

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]

# Which credential each provider prefix needs. Checked before a run, never
# during one: a job that dies on a missing key still burns wall clock and,
# depending on the provider, tokens for the trials that did start.
CREDENTIAL_ENV_BY_PREFIX = {
    "openrouter/": "OPENROUTER_API_KEY",
    "anthropic/": "ANTHROPIC_API_KEY",
    "openai/": "OPENAI_API_KEY",
    "dashscope/": "DASHSCOPE_API_KEY",
}


def credential_env_for_model(model_name: str) -> str | None:
    """Return the env var this model needs, or ``None`` when unknown."""
    value = (model_name or "").strip()
    for prefix, env_name in CREDENTIAL_ENV_BY_PREFIX.items():
        if value.startswith(prefix):
            return env_name
    return None


def resolve_model_name(explicit: str | None, env: Mapping[str, str]) -> str:
    """Explicit flag wins, else fall back to the configured persona model."""
    value = (explicit or "").strip() or str(env.get("MATRIX_PERSONA_MODEL") or "").strip()
    if not value:
        raise SystemExit(
            "no model: pass --model-name or set MATRIX_PERSONA_MODEL "
            "(application/playground/.env.local)"
        )
    return value
TASK_PATH = "application/tasks/chat_0709-vita-drive-golden-error-recovery"
RECIPE_DIR = REPO_ROOT / "configs/jobs/application-task-job-recipe"


def load_case_ids(*, per_error_type: int | None) -> list[str]:
    """Return case ids, optionally sampling evenly across error types."""
    path = REPO_ROOT / TASK_PATH / "input" / "cases.jsonl"
    cases = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    if per_error_type is None:
        return [case["case_id"] for case in cases]
    by_error_type: dict[str, list[str]] = collections.defaultdict(list)
    for case in cases:
        by_error_type[case["error_type"]].append(case["case_id"])
    return list(
        itertools.chain.from_iterable(
            sorted(ids)[:per_error_type] for _, ids in sorted(by_error_type.items())
        )
    )


def build_recipe(
    *, job_name: str, model_name: str, persona_paths: list[str], case_ids: list[str]
) -> dict[str, Any]:
    from application.scripts.vita_case_jobs import build_case_agent_entries

    return {
        "job_name": job_name,
        "jobs_dir": "jobs",
        "n_attempts": 1,
        "timeout_multiplier": 1.0,
        "n_concurrent_trials": 2,
        "quiet": False,
        # host, not docker. A chat trial drives an external HTTP SUT and needs
        # no sandbox of its own; inside the docker environment the trial
        # container cannot resolve DNS, so every SUT call dies with
        # "Temporary failure in name resolution". This mirrors what the
        # Playground backend emits for the user_sim_chat trial profile.
        "environment": {"type": "host", "delete": True},
        "agents": build_case_agent_entries(persona_paths, case_ids, model_name),
        "tasks": [{"path": TASK_PATH}],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--job-name", required=True)
    parser.add_argument("--model-name", default=None)
    parser.add_argument("--personas", required=True, nargs="+")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--smoke-per-error-type", type=int)
    group.add_argument("--all-cases", action="store_true")
    args = parser.parse_args()

    model_name = resolve_model_name(args.model_name, os.environ)

    case_ids = load_case_ids(
        per_error_type=None if args.all_cases else args.smoke_per_error_type
    )
    for persona in args.personas:
        if not (REPO_ROOT / persona).is_file():
            raise SystemExit("persona file not found: {}".format(persona))

    recipe = build_recipe(
        job_name=args.job_name,
        model_name=model_name,
        persona_paths=list(args.personas),
        case_ids=case_ids,
    )
    RECIPE_DIR.mkdir(parents=True, exist_ok=True)
    path = RECIPE_DIR / "{}.yaml".format(args.job_name)
    header = (
        "# Generated by application/scripts/generate_vita_case_job.py\n"
        "# Task: {}\n"
        "# Trial = 1 persona x 1 case | personas={} cases={} trials={}\n"
        "# Persona model: {}\n\n".format(
            TASK_PATH,
            len(args.personas),
            len(case_ids),
            len(recipe["agents"]),
            model_name,
        )
    )
    path.write_text(header + yaml.safe_dump(recipe, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print("wrote {} ({} trials)".format(path, len(recipe["agents"])))

    needed = credential_env_for_model(model_name)
    if needed is None:
        print("model {}: unknown provider, cannot check credentials".format(model_name))
    elif os.environ.get(needed, "").strip():
        print("model {}: {} is set".format(model_name, needed))
    else:
        print(
            "model {}: {} is NOT set -- this job would fail. "
            "Fix it before running, not after.".format(model_name, needed)
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
