#!/usr/bin/env python3
"""Build the driver questionnaire as a Google Apps Script, or as plain text.

The eight questions have to reach real drivers, and their answers have to come
back in a shape the crosswalk can read. Hand-typing a form invites drift between
the option labels a respondent sees and the schema values the crosswalk expects
-- one renamed option and the answer silently becomes unmappable. Both outputs
here are generated from the same questionnaire JSON, so they cannot disagree.

    --format apps-script   paste into script.google.com, Run, get a form URL
    --format text          plain text, for paper or another survey tool
    --format csv           dimension/question/label/value table, for review

Usage:
    uv run python scripts/build_vn_driver_form.py --format apps-script -o form.gs
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SPEC = (
    REPO_ROOT
    / "persona/human_extraction/standards/vn_driver_questionnaire.json"
)


def _js(text: str) -> str:
    """Escape for a JavaScript single-quoted string literal."""
    return text.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")


def as_apps_script(spec: dict, include_optional: bool) -> str:
    questions = list(spec["questions"])
    if include_optional:
        questions += spec.get("optionalQuestions", [])

    lines = [
        "// Generated by scripts/build_vn_driver_form.py -- do not hand-edit.",
        "// Paste into script.google.com, press Run, then open the logged URL.",
        "//",
        "// Option labels shown to respondents map to schema values in",
        "// {}".format(DEFAULT_SPEC.relative_to(REPO_ROOT)),
        "// The crosswalk reads the LABEL from the CSV export, so renaming an",
        "// option here without updating the questionnaire JSON breaks the join.",
        "",
        "function createForm() {",
        "  var form = FormApp.create('{}');".format(_js(spec["title"])),
        "  form.setDescription('{}');".format(_js(spec["intro"])),
        "  form.setCollectEmail(false);",
        "  form.setLimitOneResponsePerUser(false);",
        "",
    ]

    consent = spec.get("consent") or {}
    if consent.get("required"):
        lines += [
            "  form.addCheckboxItem()",
            "      .setTitle('{}')".format(_js("Đồng ý tham gia")),
            "      .setChoiceValues(['{}'])".format(_js(consent["text"])),
            "      .setRequired(true);",
            "",
        ]

    for q in questions:
        labels = ", ".join("'{}'".format(_js(o["label"])) for o in q["options"])
        lines += [
            "  // {} -> {}".format(q["dimension"], "/".join(o["value"] for o in q["options"])),
            "  form.addMultipleChoiceItem()",
            "      .setTitle('{}')".format(_js(q["text"])),
            "      .setChoiceValues([{}])".format(labels),
            "      .setRequired({});".format("true" if q.get("required", True) else "false"),
            "",
        ]

    lines += [
        "  Logger.log('Form: ' + form.getPublishedUrl());",
        "  Logger.log('Edit: ' + form.getEditUrl());",
        "}",
        "",
    ]
    return "\n".join(lines)


def as_text(spec: dict, include_optional: bool) -> str:
    questions = list(spec["questions"])
    if include_optional:
        questions += spec.get("optionalQuestions", [])

    out = [spec["title"], "=" * len(spec["title"]), "", spec["intro"], ""]
    consent = spec.get("consent") or {}
    if consent.get("required"):
        out += ["[ ] " + consent["text"], ""]
    for i, q in enumerate(questions, start=1):
        out.append("{}. {}".format(i, q["text"]))
        for o in q["options"]:
            out.append("     ( ) {}".format(o["label"]))
        if q.get("note"):
            out.append("     -- {}".format(q["note"]))
        out.append("")
    out += ["", "Quy tắc thu thập:"]
    out += ["  - " + r for r in spec.get("collectionRules", [])]
    return "\n".join(out)


def write_csv(spec: dict, include_optional: bool, path: Path) -> None:
    questions = list(spec["questions"])
    if include_optional:
        questions += spec.get("optionalQuestions", [])
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["n", "dimension", "question", "label_vi", "schema_value"])
        for i, q in enumerate(questions, start=1):
            for o in q["options"]:
                writer.writerow(
                    [i, q["dimension"], q["text"], o["label"], o["value"]]
                )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", type=Path, default=DEFAULT_SPEC)
    parser.add_argument(
        "--format", choices=("apps-script", "text", "csv"), default="apps-script"
    )
    parser.add_argument("-o", "--out", type=Path)
    parser.add_argument(
        "--include-optional",
        action="store_true",
        help="also ask cog_verbosity and vn_address_register (skip if using forum data)",
    )
    args = parser.parse_args()

    spec = json.loads(args.spec.read_text(encoding="utf-8"))
    n = len(spec["questions"]) + (
        len(spec.get("optionalQuestions", [])) if args.include_optional else 0
    )

    if args.format == "csv":
        out = args.out or Path("vn_driver_questions.csv")
        write_csv(spec, args.include_optional, out)
        print("wrote {} ({} questions)".format(out, n))
        return 0

    body = (as_apps_script if args.format == "apps-script" else as_text)(
        spec, args.include_optional
    )
    if args.out:
        args.out.write_text(body, encoding="utf-8")
        print("wrote {} ({} questions)".format(args.out, n))
    else:
        sys.stdout.write(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
