#!/usr/bin/env python3
"""Rebuild a stage-2 recipe holding only the trials that did not come back.

A stage-2 run against a live endpoint fails in bulk when the endpoint's own
quota runs out -- not because any particular conversation was wrong. Rerunning
the whole recipe would re-buy the conversations that already succeeded, so this
reads a finished job, keeps the rows whose trial raised, and writes a recipe for
exactly those.

Selection is by ``row_id``, the stimulus each trial replays, because trial
directory names are freshly minted per run and say nothing about which stimulus
went unanswered.

Usage:
    uv run python scripts/build_vita_retry_job.py jobs/vita-lab3p-s2 \\
        --recipe configs/jobs/vita-lab3p/vita-lab3p-s2.yaml \\
        -o configs/jobs/vita-lab3p/vita-lab3p-s2-retry.yaml
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent


def failed_row_ids(job_dir: Path) -> tuple[set[str], Counter]:
    """Row ids whose trial raised, plus a tally of why.

    A trial with no ``result.json`` never reported an outcome at all; it is
    counted as failed rather than skipped, since treating an absent result as a
    success would silently shrink the retry set.
    """
    failed: set[str] = set()
    reasons: Counter = Counter()
    for trial in sorted(p for p in job_dir.iterdir() if p.is_dir()):
        result_path = trial / "result.json"
        if not result_path.is_file():
            reasons["no result.json"] += 1
            continue
        try:
            result = json.loads(result_path.read_text(encoding="utf-8"))
        except ValueError:
            reasons["unreadable result.json"] += 1
            continue
        exception = result.get("exception_info")
        if not exception:
            continue
        agent = (result.get("config") or {}).get("agent") or {}
        row_id = ((agent.get("kwargs") or {}).get("seed") or {}).get("row_id")
        if row_id:
            failed.add(str(row_id))
        reasons[str(exception.get("exception_type"))] += 1
    return failed, reasons


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("job", type=Path, help="finished stage-2 job directory")
    parser.add_argument("--recipe", type=Path, required=True, help="recipe that job ran")
    parser.add_argument("-o", "--out", type=Path, required=True)
    parser.add_argument("--job-name", default=None, help="defaults to <recipe job_name>-retry")
    args = parser.parse_args()

    recipe = yaml.safe_load(args.recipe.read_text(encoding="utf-8"))
    agents: list[dict[str, Any]] = recipe.get("agents") or []
    failed, reasons = failed_row_ids(args.job)

    keep = [
        agent
        for agent in agents
        if str(((agent.get("kwargs") or {}).get("seed") or {}).get("row_id", "")) in failed
    ]

    # A recipe with no agents is accepted by the runner and does nothing, which
    # reads as "the retry ran and everything passed". Refuse instead.
    if not keep:
        print("nothing to retry: no failed trials carried a row_id present in the recipe")
        return 1

    recipe["agents"] = keep
    recipe["job_name"] = args.job_name or "{}-retry".format(recipe.get("job_name", "vita-s2"))

    header = (
        "# Generated by scripts/build_vita_retry_job.py\n"
        "# Source job: {} ({} of {} trials failed)\n"
        "# Source recipe: {}\n"
        "# Trials here: {} (only the stimuli that went unanswered)\n"
        "#\n"
        "# Run:\n"
        "#   set -a; source application/playground/.env.local; set +a\n"
        "#   export MATRIX_CHATBOT_TASK_PATH=application/tasks/chat_vita-drive-assistant\n"
        "#   export VITA_ASSISTANT_API_URL=https://<deployment-host>\n"
        "#   export VITA_APP_PASSWORD=...\n"
        "#   uv run matraix run -c {}\n"
        "#\n"
    ).format(args.job, len(failed), len(agents), args.recipe, len(keep), args.out)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        header + yaml.safe_dump(recipe, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )

    print("{} failed rows -> {} trials in {}".format(len(failed), len(keep), args.out))
    for reason, count in reasons.most_common():
        print("  {:4d}  {}".format(count, reason))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
