#!/usr/bin/env python3
"""Write one Harbor job recipe per survey task, over a whole persona pool.

Harbor's model is agents-as-trials: one task times N agents is N trials, each
agent being one persona. So a recipe here lists every persona in the pool as
an agent and names a single task, and the job produces one answered
questionnaire per persona.

The three Vita drive surveys are separate tasks and therefore separate jobs --
they ask different questions and are read as three datasets, not one.

Usage:
    uv run python scripts/generate_vn_driver_survey_jobs.py
    uv run python scripts/generate_vn_driver_survey_jobs.py --limit 3
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import yaml

SCRIPTS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS_DIR))
from persona_tiers import persona_paths as pool_persona_paths  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent

TASKS = (
    "vita-drive-experience",
    "vita-drive-safety-trust",
    "vita-drive-soul-persona",
)

# The persona block used to run ~7,700 tokens because these carried 1,291
# dimensions. The pool now holds 31 fields and the prompt renders 19 of them,
# so the block is under 900 characters -- the window is left generous anyway,
# because the questionnaire is the large half.
MAX_INPUT_TOKENS = 72000
MAX_OUTPUT_TOKENS = 16384


def persona_entries(pool: Path, limit: int | None) -> list[tuple[str, str, Path]]:
    """(persona_id, display_name, path) for a pool.

    Named apart from ``pool_persona_paths``: it used to shadow the import it
    calls, so the function recursed into itself and the generator could not run
    at all.
    """
    out = []
    for path in pool_persona_paths(pool):
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        out.append((raw.get("persona_id") or path.stem, raw.get("display_name") or "", path))
    return out[:limit] if limit else out


def _rel(path: Path) -> str:
    """Repo-relative, so a generated recipe is identical on any machine."""
    try:
        return str(Path(path).resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def write_recipe(task: str, personas: list, model: str, concurrency: int, out_dir: Path, pool: Path) -> Path:
    job = "vn-drv-full-{}".format(task.replace("vita-drive-", ""))
    lines = [
        "# Generated by scripts/generate_vn_driver_survey_jobs.py",
        "# Task: survey_{}".format(task),
        "# Personas: {} from {}".format(len(personas), _rel(pool)),
        "#",
        "# Run:",
        "#   export MATRIX_SURVEY_TASK_PATH=application/tasks/survey_{}".format(task),
        "#   uv run matraix run -c configs/jobs/vn-driver-surveys/{}.yaml".format(job),
        "#",
        "job_name: {}".format(job),
        "jobs_dir: jobs",
        "n_attempts: 1",
        "timeout_multiplier: 1.0",
        "n_concurrent_trials: {}".format(concurrency),
        "quiet: false",
        "environment:",
        "  type: host",
        "  delete: true",
        "agents:",
    ]
    for persona_id, name, path in personas:
        rel = _rel(path)
        lines += [
            "# {}".format(name) if name else "#",
            "- name: persona-json-survey",
            "  model_name: {}".format(model),
            "  kwargs:",
            "    persona_path: {}".format(rel),
            "    model_info:",
            "      max_input_tokens: {}".format(MAX_INPUT_TOKENS),
            "      max_output_tokens: {}".format(MAX_OUTPUT_TOKENS),
        ]
    lines += ["tasks:", "- path: application/tasks/survey_{}".format(task), ""]
    out_dir.mkdir(parents=True, exist_ok=True)
    dest = out_dir / "{}.yaml".format(job)
    dest.write_text("\n".join(lines), encoding="utf-8")
    return dest


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pool", type=Path, default=REPO_ROOT / "persona/datasets/vn-drivers")
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "configs/jobs/vn-driver-surveys")
    ap.add_argument(
        "--model",
        default=os.environ.get(
            "MATRIX_PERSONA_MODEL", "openrouter/google/gemini-3.5-flash-lite"
        ),
    )
    ap.add_argument("--concurrency", type=int, default=8)
    ap.add_argument("--limit", type=int, default=None, help="use only the first N personas")
    args = ap.parse_args()

    personas = persona_entries(args.pool, args.limit)
    if not personas:
        raise SystemExit("no personas under {}".format(args.pool))
    for task in TASKS:
        dest = write_recipe(task, personas, args.model, args.concurrency, args.out, args.pool)
        print("WROTE {}  ({} personas x 1 task = {} trials)".format(
            _rel(dest), len(personas), len(personas)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
