#!/usr/bin/env python3
"""Emit one stage-1 survey recipe per utterance intent, for a fixed persona set.

Stage 1 asks each persona to write ``scenario`` + ``first_input`` for every cell
of an intent's grid; stage 2 then replays those rows as conversations. Only the
navigation intent had been run, so a multi-intent stage-2 needs the remaining
intents generated by the SAME personas -- otherwise intent and persona are
confounded and no comparison across intents means anything.

Usage:
    uv run python scripts/generate_vita_stage1_jobs.py \\
        --persona wiki-62c08cb727c5 --persona wiki-62706e3ac3c2 \\
        --skip-intent journey-navigation-places --out-dir configs/jobs/vita-stage1
"""

from __future__ import annotations

import argparse
import glob
import os
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "src"))

from matraix.persona_agent_context import (  # noqa: E402
    apply_persona_context_to_agent_spec,
)

TASK_GLOB = "application/tasks/survey_vita-utterance-*"
AGENT = "persona-json-survey"
# The model id belongs to whichever endpoint OPENROUTER_API_BASE points at --
# OpenRouter wants "google/gemini-...", Google's own OpenAI-compatible endpoint
# 404s on that and wants the bare id. Reading the env keeps one repo working
# against both, the way the locale-pack scripts already do.
DEFAULT_MODEL = os.environ.get(
    "MATRIX_PERSONA_MODEL", "openrouter/google/gemini-3.5-flash-lite"
)


def persona_path_for(persona_id: str, pool: str | None = None) -> str:
    # Without ``pool`` the first path in sort order wins silently, which is
    # wrong once two pools carry the same persona_ids.
    root = "persona/datasets/{}/**".format(pool) if pool else "persona/datasets/**"
    matches = sorted(
        glob.glob(
            str(REPO_ROOT / root / f"persona_{persona_id}.yaml"),
            recursive=True,
        )
    )
    if not matches:
        raise SystemExit("no persona yaml for id {!r}".format(persona_id))
    return str(Path(matches[0]).relative_to(REPO_ROOT))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--persona", action="append", required=True, dest="personas")
    parser.add_argument("--skip-intent", action="append", default=[], dest="skips")
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument(
        "--persona-pool",
        help="directory under persona/datasets to resolve personas from",
    )
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--job-prefix", default="vita-s1")
    parser.add_argument("--n-concurrent", type=int, default=3)
    args = parser.parse_args()

    paths = [str(Path(p).relative_to(REPO_ROOT)) for p in sorted(glob.glob(str(REPO_ROOT / TASK_GLOB)))]
    persona_paths = [persona_path_for(p, args.persona_pool) for p in args.personas]
    args.out_dir.mkdir(parents=True, exist_ok=True)

    written = []
    for task in paths:
        slug = Path(task).name.replace("survey_vita-utterance-", "")
        if slug in args.skips:
            continue
        job_name = "{}-{}".format(args.job_prefix, slug)
        job = {
            "job_name": job_name,
            "jobs_dir": "jobs",
            "n_attempts": 1,
            "timeout_multiplier": 1.0,
            "n_concurrent_trials": args.n_concurrent,
            "quiet": False,
            "environment": {"type": "host", "delete": True},
            "agents": [
                apply_persona_context_to_agent_spec(
                    {
                        "name": AGENT,
                        "model_name": args.model,
                        "kwargs": {"persona_path": path},
                    },
                    model_name=args.model,
                )
                for path in persona_paths
            ],
            "tasks": [{"path": task}],
        }
        out = args.out_dir / "{}.yaml".format(job_name)
        header = (
            "# Generated by scripts/generate_vita_stage1_jobs.py\n"
            "# Intent: {}\n"
            "# Personas: {}\n"
            "#\n"
            "# Run:\n"
            "#   export MATRIX_SURVEY_TASK_PATH={}\n"
            "#   uv run matraix run -c {}\n"
            "#\n"
        ).format(slug, ", ".join(args.personas), task, out)
        out.write_text(
            header + yaml.safe_dump(job, sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
        written.append((job_name, task, out))

    for job_name, task, out in written:
        print("{}  ->  {}".format(job_name, out))
    print(
        "\n{} jobs x {} personas = {} stage-1 trials".format(
            len(written), len(persona_paths), len(written) * len(persona_paths)
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
